### PR TITLE
Switch from Yarn and npx to pnpm 

### PR DESCRIPTION
**Pull request by ProchaLu**
This PR updates the project's package manager from Yarn and npx to pnpm for dependency management. Previously, we used Yarn as our package manager for the students, but now we switched to pnpm. 

The main change is in the commands used to manage dependencies. Instead of using `yarn` and `npx` to manage dependencies and execute commands, we will only use `pnpm`.

### CODE REVIEW

**Review by hola-soy-milk — APPROVED** [review]
Dope, thank you so much!

**Comment by karlhorky** [comment]
Wonder if this new `@rnx-kit/metro-resolver-symlinks` could be used also with an Expo project... 🤔 (to avoid the `node-linker=hoist` in pnpm)

https://github.com/facebook/metro/issues/1#issuecomment-1508403519

**Comment by karlhorky** [comment]
Looks like this `kitchen-sink` Expo app is using it 👀

https://github.com/tamagui/tamagui/blob/fd7105ebf1ce6feb362dcad5da64f205e6b71b69/apps/kitchen-sink/metro.config.js#L2-L9

**Comment by karlhorky** [comment]
Opened an issue to explore it further:

- https://github.com/hola-soy-milk/upleveled-react-native-expo/issues/6

**Pull request merged**
